FROM runpod/worker-comfyui:5.4.1-base

RUN comfy model download --url https://civitai.com/api/download/models/1190596?token=50aca1e35b442c46ab614b172982822b --relative-path models/checkpoints --filename noobaiXLNAIXL_vPred10Version.safetensors